#! /bin/bash

current_branch=$(git rev-parse --abbrev-ref HEAD)
dev_branch=${1:-dev}
function is_dev_branch_updated() {
  echo "Check whether ${dev_branch} is update: "
  git fetch 
  behind=$(git rev-list --count $dev_branch..origin/$dev_branch)
  if [ $behind -gt 0 ]
  then
    echo "Please update and merge ${dev_branch} --> ${current_branch} branch"
    echo "  before pushing to repository in order to prevent conflict"
    echo "  \$git fetch"
    echo "  \$git merge ${dev_branch}"
    return -1
  fi
  return 0
}

is_dev_branch_updated
